---
# Variables par défaut pour Node Exporter

# Version par défaut (peut être surchargée par group_vars/all ou monitoring_hosts)
node_exporter_version: "1.7.0"

# Port d'écoute par défaut
node_exporter_port: 9100

node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_bin_dir: "/usr/local/bin"
node_exporter_install_dir: "/opt/node_exporter"
node_exporter_service_name: "node_exporter"
