$ANSIBLE_VAULT;1.1;AES256
38376230643636636432653162613762383934376432303737623331366365623962666162333762
3537633438633738333734616534336636306266626632640a633864636334313937663862316630
64613033316266626334626331646161646664633665393165663931666137383633633031373863
3566346137386465300a633736646536633465306261313661646666316262313731346335353264
62376365373234383763313633613939613863316430613234393161653038333837643366613833
30623437613834333034613636316434363834313131643165363162383964313939383632663039
65623935316463336165616262383062376261323838366133663963633332666232333732616666
66316464366164303164393763626331376464353736623431656639343732303039656363636431
32306336326636613739313333356233303638373833343463633062313835396337636330663163
6337616266623863623564636161613637383833623030653931
