---
- name: restart gitlab
  community.docker.docker_compose_v2:
    project_src: /srv/gitlab
    state: restarted
  become: true

- name: restart runner
  community.docker.docker_compose_v2:
    project_src: /srv/gitlab
    state: restarted
  become: true
