---
- name: restart gitlab
  ansible.builtin.command:
    cmd: docker compose restart gitlab
    chdir: /srv/gitlab
  become: true

- name: restart runner
  ansible.builtin.command:
    cmd: docker compose restart gitlab-runner
    chdir: /srv/gitlab
  become: true
