---
taiga_postgres_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66343433343837373931313839346466363266623733323864386132663339393565616531373635
          3561363466663764646536333062393130313130363130340a346335313166623039323864363531
          38646263343439396665393262306162383565396262623938313233376136386162616363373131
          3065333033353431340a633466333266663965646234623763376139616165313666663433306635
          3362


taiga_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61363232633436613534326137663137616132336239393738323766353966303231633831623731
          3738373065363234303031633564306565633964623065320a363732353937646636336365313931
          65326430636234646263653766613635663861653436373163646661356666366534333339346435
          3734353461333665360a356663626263353665613063623935386662393662336463373938366139
          6661
