---
- name: Preconditions for Nginx reverse proxy
  ansible.builtin.import_tasks: prerequisites.yml

- name: Install Nginx reverse proxy dependencies
  ansible.builtin.import_tasks: install.yml

- name: Configure Nginx reverse proxy files
  ansible.builtin.import_tasks: configure.yml

- name: Deploy Nginx reverse proxy stack
  ansible.builtin.import_tasks: deploy.yml

- name: Apply Nginx reverse proxy security hardening
  ansible.builtin.import_tasks: security.yml

- name: Validate Nginx reverse proxy deployment
  ansible.builtin.import_tasks: validation.yml
