---
nginx_rp_domain: "lab.local"
nginx_rp_ip: "172.16.100.253"
nginx_rp_https_port: 443
nginx_rp_ssl_dir: "/etc/nginx/ssl"

nginx_rp_backends:
  harbor:
    host: "172.16.100.50"
    port: 80
  portainer:
    host: "172.16.100.50"
    port: 9000
  gitlab:
    host: "172.16.100.40"
    port: 8181
  gitlab_registry:
    host: "172.16.100.40"
    port: 5050
  taiga:
    host: "172.16.100.20"
    port: 9000
  edgedoc:
    host: "172.16.100.20"
    port: 8080
  grafana:
    host: "172.16.100.60"
    port: 3000
  prometheus:
    host: "172.16.100.60"
    port: 9090
  alertmanager:
    host: "172.16.100.60"
    port: 9093
gitlab_registry: "registry.lab.local:5000"
