all:
  children:
    bind9_hosts:
      hosts:
        bind9dns:
          ansible_host: 172.16.100.254
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common

    reverse_proxy_hosts:
      hosts:
        reverse-proxy:
          ansible_host: 172.16.100.253
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common

    tools_hosts:
      hosts:
        tools-manager:
          ansible_host: 172.16.100.20
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common

    harbor_portainer_hosts:
      hosts:
        harbor:
          ansible_host: 172.16.100.50
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common

    gitlab_hosts:
      hosts:
        git-lab:
          ansible_host: 172.16.100.40
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common

    monitoring_hosts:
      hosts:
        monitoring-stack:
          ansible_host: 172.16.100.60
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common

    k3s_manager_hosts:
      hosts:
        k3s-manager:
          ansible_host: 172.16.100.250
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common

    k3s_worker_hosts:
      hosts:
        k3s-worker-0:
          ansible_host: 172.16.100.251
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common
        k3s-worker-1:
          ansible_host: 172.16.100.252
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_common
