all:
  children:
    bind9_hosts:
      hosts:
        bind9dns:
          ansible_host: 172.16.100.254

    taiga_hosts:
      hosts:
        tools-manager:
          ansible_host: 172.16.100.20

    harbor_portainer_hosts:
      hosts:
        harbor: {}
