---
galaxy_info:
  author: Projet infra devops
  description: "Déploiement d'un conteneur Docker Bind9 sécurisé et idempotent"
  company: ""
  license: MIT-0
  min_ansible_version: "2.13"
  galaxy_tags:
    - bind9
    - dns
    - docker
    - devops
    - networking

dependencies: []
