---
# Defaults for Harbor role (Mission 2)

harbor_version: "v2.11.1"
harbor_offline_installer_url: "https://github.com/goharbor/harbor/releases/download/{{ harbor_version }}/harbor-offline-installer-{{ harbor_version }}.tgz"

harbor_install_dir: "/opt/harbor"
harbor_data_dir: "/data/harbor"

harbor_hostname: "harbor.lab.local"
harbor_http_port: 80
harbor_external_url: "https://harbor.lab.local"

harbor_admin_password: "ChangeMe!HarborAdmin"  # Ã  surcharger via vault

harbor_trivy_enabled: true

harbor_firewall_rules:
  - { port: 80,   allowed_ip: "172.16.100.253" }

harbor_compose_project_name: "harbor"
